jobs:
  build:
    name: Release build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        password: ${{ secrets.ELLIE_MINI_SECRET }}
      name: Remove work folders
      run: 'echo "before"

        ls -lah ./

        echo $password | sudo -S rm -rf ./* || true

        echo $password | sudo -S rm -rf ./.??* || true

        echo "after"

        ls -lah ./

        '
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Checkout repository submodules
      run: git submodule update --init --recursive
    - continue-on-error: true
      id: gl4es-sha
      name: Get gl4es latest commit hash
      run: echo "::set-output name=sha::$(echo $(git ls-remote https://github.com/PojavLauncherTeam/gl4es-114-extra
        refs/heads/master | grep -io '^\S*'))"
      shell: bash
    - continue-on-error: true
      id: gl4es-cache
      if: false
      name: Cache gl4es
      uses: actions/cache@v3
      with:
        key: gl4es-holy-ios-shared-2-${{ steps.gl4es-sha.outputs.sha }}
        path: gl4es/libs
    - continue-on-error: true
      if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
      name: Get gl4es
      uses: actions/checkout@v3
      with:
        path: gl4es
        repository: PojavLauncherTeam/gl4es-114-extra
    - continue-on-error: true
      if: false && steps.gl4es-cache.outputs.cache-hit != 'true'
      name: Build gl4es
      run: "cd gl4es\ngit config --global user.email \"github-actions@users.noreply.github.com\"\
        \ngit config --global user.name \"github-actions\"\nexport PATH=/opt/procursus/bin:$PATH\n\
        wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake\n\
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 \\\
        \n  -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \\\n  -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration\n\
        cmake --build build --config RelWithDebInfo --target GL\ncp -R lib/libGL.dylib\
        \ ../Natives/resources/Frameworks/libgl4es_114.dylib\n"
    - continue-on-error: true
      if: false && github.event != 'pull_request' && github.ref_name == 'main' &&
        steps.gl4es-cache.outputs.cache-hit != 'true'
      name: Push gl4es
      run: 'git add Natives/resources/Frameworks/libgl4es_114.dylib

        git commit -am "CI: Update gl4es"

        git push

        '
    - continue-on-error: true
      name: Get JRE8
      uses: dawidd6/action-download-artifact@v2
      with:
        allow_forks: false
        branch: jre8-ios-jitjailed
        github_token: ${{secrets.GITHUB_TOKEN}}
        name: jre8-ios-aarch64
        path: depends
        repo: PojavLauncherTeam/android-openjdk-build-multiarch
        workflow: build.yml
        workflow_conclusion: success
    - continue-on-error: true
      name: Get JRE17
      uses: dawidd6/action-download-artifact@v2
      with:
        allow_forks: false
        branch: buildjre17
        github_token: ${{secrets.GITHUB_TOKEN}}
        name: jre17-ios-aarch64
        path: depends
        repo: PojavLauncherTeam/android-openjdk-build-multiarch
        workflow: build.yml
        workflow_conclusion: success
    - continue-on-error: true
      env:
        password: ${{ secrets.ELLIE_MINI_SECRET }}
      name: Build for ${{ matrix.platform_name }}
      run: "export PATH=/opt/procursus/bin:/opt/homebrew/bin:$PATH\nexport RUNNER=1\n\
        gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{ matrix.platform }}\n\
        # Additionally build TrollStore (auto JIT) tipa for iOS\nif [ \"${{ matrix.platform_name\
        \ }}\" == \"ios\" ]; then\n  gmake -j$(sysctl -n hw.ncpu) dsym package PLATFORM=${{\
        \ matrix.platform }} TROLLSTORE_JIT_ENT=1\nfi\n"
    - continue-on-error: true
      name: Upload regular ipa
      uses: actions/upload-artifact@v3
      with:
        name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.ipa
        path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}.ipa
    - continue-on-error: true
      name: Upload regular tipa
      uses: actions/upload-artifact@v3
      with:
        name: net.kdt.pojavlauncher-${{ matrix.platform_name }}.tipa
        path: artifacts/net.kdt.pojavlauncher-*-${{ matrix.platform_name }}-trollstore.tipa
    - continue-on-error: true
      name: Upload PojavLauncher.dSYM
      uses: actions/upload-artifact@v3
      with:
        name: PojavLauncher.dSYM
        path: artifacts/PojavLauncher.dSYM
    strategy:
      matrix:
        include:
        - platform: 2
          platform_name: ios
        - platform: 3
          platform_name: tvos
        - platform: 7
          platform_name: iossimulator
        - platform: 8
          platform_name: tvossimulator
name: Release build
on:
  repository_dispatch:
    types: trigger-ga___release.yml
